# -*- coding: utf-8 -*-
"""EDGe course.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDXVK20YBeI6k8blITN6olDahr_QiD59

print("Welcome to EDGE course")
print("Welcome to data science world")
print("My deparment name is Statistics")
"""

def calculator():
  a= eval(input("enter any Number "))
  b=eval(input("Enter any number"))
  operation= input("enter your operation sign from this list[+ - * /]")
  if operation=="+":
    print(a+b)
  elif operation=="-":
    print(a-b)
  elif operation=="*":
    print(a*b)
  elif operation=="/":
    print(a/b)
calculator()



print("Welcome to EDGE course")
print("Welcome to data science world")
print("My deparment name is Statistics")

num1= 10
temperature=36.7
Name="Sakib"
boolean= True
print(f"The value is",num1,"which is integer")
print(f"The value is",temperature,"which is float")
print(f"The value is",Name,"which is string")

a=10
b=10
c= a==b
print(c)

"""d=a!=b
print(d)
"""

d=a!=b
print(d)

age=20
if age>=18:
  print("You are eligible for vote")
else:
  print("You are not eligible for vote")

def getmarry():
  age=int(input("Enter your age: "))
  gender=input("Enter your gender: ")
  if age>=18 and gender=="female":
    print("Youge are eligible for marriage")
  elif age>=21 and gender=="male":
    print("You are eligible for marriage")
  else:
    print("Enter gender as female or male")
getmarry()

"""Given the weight and height of
a person, calculate his BMI.
You may have to use the
internet for the formula.
"""

def Bmi():
  weight=eval(input("Enter your weight in in kilograms: "))
  height=eval(input("Enter your Height in inch: "))
  #transforming height in inch to metre

  heightm=height*0.0254

  #calculation of BMI by using formula
  BMI=weight/heightm**2
  print(f"Your BMI is {BMI}")

  if BMI<18.5:
    print("You are underweight")
  elif BMI>=18.5 and BMI<=24.9:
    print("You are normal")
  elif BMI>=25 and BMI<=29.9:
    print("You are overweight")
  else:
    print("You are obese")
Bmi()





"""You’ll be given a double value
t as input. t represents a
temperature in celsius. Print
converting it to the
fahrenheit.
"""

temp_cel= float(input("Enter the temperature in celsius: "))
#transforming temperature into farenheit from celcius using mathematical formula

temp_far=(temp_cel*9/5)+32
print(f"Temperature in farenheit scale is {temp_far}")

"""You will be given 3 side
lengths of a triangle find
whether its equilateral or not.
"""

#take the value of lenght of side of triangle as input
a=eval(input("enter the length of side a: "))
b=eval(input("enter the length of side b: "))
c=eval(input("enter the length of side c: "))

#chekc the equality

if a==b==c:
  print("The triangle is equilateral")
else:
  print("The triangle is not equilateral")



"""You will be given 4 lengths,
check whether its possible to
form a rectangle with it.

"""

def is_rectangle(a, b, c, d):
    sides = sorted([a, b, c, d])
    return sides[0] == sides[1] and sides[2] == sides[3]
a = int(input("Enter the length of side a: "))
b = int(input("Enter the length of side b: "))
c = int(input("Enter the length of side c: "))
d = int(input("Enter the length of side d: "))

if is_rectangle(a, b, c, d):
    print("It is possible to form a rectangle.")
else:

    print("It is not possible to form a rectangle.")

#Print all the even numbers from
#1 to 1000
even_num=[]
for i in range(1,1001):
  if i%2==0:
    even_num.append(i)
print(even_num)

#Check whether a given number nis prime or not.
def is_prime():
  num=int(input("Enter a number: "))
  if num>1:
    for i in range(2,num):
      if num%i==0:
        print(f"{num} is not a prime number")
        break
    else:
      print(f"{num} is a prime number")
  else:
    print(f"{num} is not a prime number")
is_prime()

import pandas as pd
import numpy as np

n= int(input("Enter a number: "))
df= pd.DataFrame((np.random.randint(0,n, size=(4,5))),index=["a","b","c","d"])
print(df)

"""#4th day of EDGE course
by  Sahadat sir **bold text**
"""

age=12
print(age, type(age))
age=str(age)
print(age, type(age))
age="True"
print(age,type(age))
age=bool(age)
print(age,type(age))

a=85
b= 12
print("summantion ", a+b)
print("Subtraction",a-b)
print("Multiplication ", a*b)
print("Division ", a/b)
print("modulus ",a%b)
print("Round ",a//b)
print("power ",a**b)
print("bth root of a ", a**(1/b))

s="25"
result= int(s)+10
print(result)

num1= 5
num2=10
print(num1>num2)
if num1>num2:
  print("Number 1 is greater than number 2")
else:
  print("Number 2 is greater than number 1")

from re import T
#define variables
a=True
b=False
#logical AND
print(a,"and",b,":", a and b)
print(a,"and",not b,":", a and not b)
print(not a,"and",b,":", not a and b)
print(not a,"and",not b,":", not a and not b)
#logical OR
print(a,"or",b,":", a or b)
print(a," or",not b,":", a or not b)
print(not a,"or",b,":", not a or b)
print(not a,"or",not b,":", not a or not b)

#logical NOT
print('not',a,":", not a)
print('not',b,":", not b)

x=5
y=10
print(x<y or x>y)
print(not x<y or x>y)
print(x<y or not x>y)
print(not x<y or not x>y)

x=5
y=10
print(x<y and x>y)
print(not x<y and x>y)
print(x<y and not x>y)
print(not x<y and not x>y)

a= input("Enter first number: ")
b= input("Enter second number: ")
sum= a+b
print("summation ", sum)

#in the above example value of a and b are taken as string thatst why result is concatanated
a=eval( input("Enter first number: "))
b= eval(input("Enter second number: "))
sum= a+b
print("summation ", sum)

a= 5
b=10
print(a>b)
if a>b:
  print("a is greater than b")
else:
  print("b is greater than a")

a= 5
b=10
print(a>b)
if a>b:
  print("a is greater than b")
elif a==b:
  print("a is equal to b")
else:
  print("b is greater than ")

x=10
if x<5:
  print("less than 5")
elif x<15:
  print("less than 15")
else:
  print("15 or more")

marks= int(input ("Enter your marks: "))
total_marks= int(input("Enter total marks: "))
percentage= (marks/total_marks)*100

if percentage>=80:
  print("Grade A+")
elif percentage>=75:
  print("Grade A")
elif percentage>=71:
  print("Grade A-")
elif percentage>=66:
  print("Grade B+")
elif percentage>=61:
  print("Grade B")
elif percentage>=56:
  print("Grade B-")
elif percentage>=51:
  print("Grade C+")
elif percentage>=46:
  print("Grade C")
elif percentage>=40:
  print("Grade D")
else:
  print("Grade F")

#checking syntax error by providing elseif instead of elif
x=10
if x<5:
  print("less than 5")
elseif x<15:
  print("less than 15")
else:
  print("15 or more")

a=200
b=33
c=5000
if a>b and c>a:
  print("Both condition are true")

a=200
b=33
if a>b:
  print("a in Not greater than b")



"""5th day of EDGE course"""

#while loop practice
i = 1
while i < 6:
  print(i)
  if i == 3:
    break
    #loop will stop when i=3 thats mean break function will stop when a certain
    #when a certain condition is satisfied
  i += 1

i = 1
while i < 6:
  i += 1
  if i == 3:
    continue
  print(i)

"""6th day of EDGE course

"""

#To test whether a year is leap or not
def leap_year():
  try:
    year=eval(input("Enter a year: "))
    if year%4==0 and year%100!=0 or year%400==0:
      print(f"{year} is a leap year")
    else:
      print(f"{year} is not a leap year")
  except Exception as e:
    print(e)
leap_year()



# Finding grade result
marks= int(input ("Enter your marks: "))
total_marks= int(input("Enter total marks: "))
percentage= (marks/total_marks)*100

if percentage>=80:
  print("Grade A+")
elif percentage>=75:
  print("Grade A")
elif percentage>=70:
  print("Grade A-")
elif percentage>=65:
  print("Grade B+")
elif percentage>=60:
  print("Grade B")
elif percentage>=55:
  print("Grade B-")
elif percentage>=50:
  print("Grade C+")
elif percentage>=45:
  print("Grade C")
elif percentage>=40:
  print("Grade D")
else:
  print("Grade F")

#Find BMI
def Bmi():
  weight=eval(input("Enter your weight in in kilograms: "))
  height=eval(input("Enter your Height in inch: "))
  #transforming height in inch to metre

  heightm=height*0.0254

  #calculation of BMI by using formula
  BMI=round(weight/heightm**2,2)
  print(f"Your BMI is {BMI}")
#BMI status check
  if BMI<18.5:
    print("You are underweight")
  elif BMI>=18.5 and BMI<=24.9:
    print("You are normal")
  elif BMI>=25 and BMI<=29.9:
    print("You are overweight")
  else:
    print("You are obese")
Bmi()

#Nested loop
"""find the pattern
1
1 2
1 2 3
1 2 3 4
1 2 3 4 5"""

#solution
row= int(input("Enter number of rows: "))
for i in range(1,row+1):
  for j in range(1,i+1):
    print(j,end=" ")

import numpy as np
import statistics as stat
num=[19,34,56,23,23,23,46,78,90,]
num1=[50,60,70,80,80,90,50,100]
print(np.mean(num))
print(np.median(num))
print(stat.mode(num))
print(np.mean(num1))
print(np.median(num1))
print(stat.mode(num1))

print(stat.multimode(num1))

cname= str(input("Enter a country name: ")).upper()
SAARC=['BANGLADESH','INDIA','NEPAL','MALAYSIA','PAKISTAN','AFGANISTAN','BHUTAN','SRILANKA']
if cname in SAARC:
  print(f"{cname} is a member of SAARC")
else:
  print(f"{cname} is not a member of SAARC")

"""7th day of EDGE **course**

> Add blockquote


"""

#more lecture of loop
for i in range(23,30,2):

  print(i)

a=23
b=30

while a<b:
  print(a)
  a=a+2

n=int(input("Enter a number: "))

for i in range(1,n+1):
  if i%2==0:
    print(f"Even numbers are {i}")
  else:
    print(f"Odd numbers are {i}")

n=int(input("Enter a number: "))
even_num=[]
odd_num=[]
for i in range(1,n+1):
  if i%2==0:
    even_num.append(i)
  else:
    odd_num.append(i)
print(f"all even number are {even_num}")
print(f"all odd number are {odd_num}")

for i in "banana":
  print(i)

fruits=["apple","banana","cherry"]
for i in fruits:

  #break after banana
  if i=="cherry":
    break
  print(i)

fruits=["apple","banana","cherry"]
for i in fruits:

  #break after banana
  if i=="banana":
    continue
  print(i)

for i in range(6):
  print(i,end=" ")

for i in range (6):
  print(i,end=" ")
else:
  print("Finally finished")

for i in range(6):
  if i ==3:
    break
  print(i,end=" ")
else:
  print("Finally finished")

adj=["red","big","tasty"]
price=[100,200,300]
for i in adj:
  for j in fruits:
    for k in price:
      print(i,j,k)

# i have two list, such as adj=["red","big","tasty"] and
# price=[100,200,300]. If I want output as red 100 , big 200, tasty 300.

adj = ["red", "big", "tasty"]
price = [100, 200, 300]

for i in range(len(adj)):
  print(adj[i], price[i])

i=1
while i<6:
  print(i)
  i+=1

i=1
while i<6:
  print(i)
  if i==3:
    break
  i+=1

i=1
while i<6:

  print(i)
  i+=1
  if i==3:
    continue

i=1
while i<6:
  print(i)
  i+=1
else:
  print("1 is no longer less than 6")

#lecture on function

def my_function():
  print("Hello form a function")

#calling the function
my_function()

def my_function(fname):
  print(fname + " Refsnes")

my_function("Emil")
my_function("Tobias")
my_function("Linus")

def my_function(fname,lname):
  print(fname+" "+lname)
my_function("Emil","Refnes")

def my_func(*kid):
  print("The youngest child is "+kid[2])
my_func("Emil","Tobias","Linus")

def my_func(food):
  for i in food:
    print(i)
my_func(fruits)#fruits is a list which is run earlier

def myfunction(x):
  return 5*x
print(myfunction(3))
print(myfunction(5))
print(myfunction(9))

def myfunction():
  pass

def multiply(a,b):
  m=a*b
  return m
ans=multiply(5,6)
print(ans)

#Find BMI
def Bmi():
  weight=eval(input("Enter your weight in in kilograms: "))
  height=eval(input("Enter your Height in inch: "))
  #transforming height in inch to metre

  heightm=height*0.0254

  #calculation of BMI by using formula
  BMI=round(weight/heightm**2,2)
  print(f"Your BMI is {BMI}")
#BMI status check
  if BMI<18.5:
    print("You are underweight")
  elif BMI>=18.5 and BMI<=24.9:
    print("You are normal")
  elif BMI>=25 and BMI<=29.9:
    print("You are overweight")
  else:
    print("You are obese")
Bmi()

# sort vlaue using nested loop
def bubble_sort(arr):
  n=len(arr)
  for i in range(n):
    for j in range(0,n-i-1):
      if arr[j]>arr[j+1]:
        arr[j],arr[j+1]=arr[j+1] ,arr[j]
  return arr
arr=[64,34,25,12,12,22,11,90]
print(bubble_sort(arr))

def sort(arr):
  sorted_arr=[]
  n=len(arr)
  for i in range(n):
    minimum_vlaue=min(arr)
    arr.remove(minimum_vlaue)
    sorted_arr.append(minimum_vlaue)
  return sorted_arr
arr=[64,34,25,12,12,22,11,90]
print(sort(arr))

"""8 th day of EDGE COURse"""



# print this following pattern
"""*****
****
***
**
*"""
#to print this we need to use nested loop

#first take the number of rows

rows=int(input("Enter the number of rows: "))
for i in range(rows,0,-1): #as usual we start range function small to large but
#here we take range function argument value frome large to small that
#so increment is -1



  for j in range(0,i):
    print("#",end=" ")
  print()

# print the following pattern
"""1
1 4
1 4 9
 1 4 9 16
 1 4 9 16 25 """

row= int(input("enter the number of rows: "))
for i in range(1,row+1):
  for j in range(1,i+1):
    print(j**2, end=" ")
  print()

#function definition
def add():

  a=eval(input("Enter first number: "))
  b=eval(input("Enter second number: "))
  return a+b
  print(f"sum of {num1} and {num2} is {sum}")
add()

def add(a,b):
  return a+b
num1=int(input("Enter first number: "))
num2=int(input("Enter second number: "))
sum=add(num1,num2)
print(f"sum of {num1} and {num2} is {sum}")

#my_list=[1,2,3,'four',5.0]
print(my_list[-1])
print(my_list[2:4])

#modifying a list
my_list[2]=6
print(my_list)

namelist=["Harsh","Pratik","Bob","Dhrubv"]
print(namelist[1][-1])

#slicing the list
print(my_list[2:5])

print(my_list[-3:-1])

#iterating a list using for loop
for element in my_list:
  print(element)

my_list.append(8)
print(my_list)

geekcodes=[1,2,3,4]
geekcodes.append([5,6,7,8])
print(geekcodes)

geekcodes=[1,2,3,4]
geekcodes.insert(1,[80,90])
print(geekcodes)

print(my_list.remove("four"))

li=[2,3.4,'Orange',8,'apples']
li.append("mango")
li.insert(8,5)
print(li)

print(my_list.extend(geekcodes))

firstname= "Junayed "
middlename= "Mohammed "
lastname= "Sakib"
fullname=firstname+middlename+lastname
print(fullname)

text="dhaka is the CAPITAL of bangladesh"
print(text.upper())
print(text.lower())
print(text.capitalize())
print(text.swapcase())
print(text.title())

mydic={}
my_dict={"name":"Alice","age":25,"city":"New York"}
print(my_dict)

get= my_dict.get("age")
print(get)

#updating existing key
my_dict["age"]=30
print(my_dict)

#Add new key-value
my_dict["Profssion"]="Engineer"
print(my_dict)

def factorial(n):

  result=1
  for i in range(2,n+1):
    result=result*i
  return result


factorial(10)



def calculator():
  a= eval(input("enter any Number "))
  b=eval(input("Enter any number"))
  operation= input("enter your operation sign from this list[+ - * /]")
  if operation=="+":
    print(a+b)
  elif operation=="-":
    print(a-b)
  elif operation=="*":
    print(a*b)
  elif operation=="/":
    print(a/b)
calculator()







def calculate(num1,num2,operator):
  if operator=="+":
    return num1+num2
  elif operator=="-":
    return num1-num2
  elif operator=="*":
    return num1*num2
  elif operator=="/":
    if num2==0:

      print("In division denumerator can't never be zero")
    else:
      return num1/num2
  else:
    print("Invalid operator or operand")

while True:
  user_input=input("Enter calculation (e.g- 2+3)or type exit to quite ").strip()
  if user_input.lower()=="exit":
    print("exiting program")
    break
  else:
    parts = user_input.split()

    num1=eval(parts[0])
    num2=eval(parts[2])
    operator= parts[1]

    result= calculate(num1,num2,operator)





    print(result);

import pandas as pd

